;;  ergoemacs-mode
(setq ergoemacs-theme nil)
(setq ergoemacs-keyboard-layout "us")
(require-package 'ergoemacs-mode)
(setq ergoemacs-handle-ctl-c-or-ctl-x 'both)
(ergoemacs-mode 1)
;; the following remap is need only under windows' emacs
(when *windows*
  (define-key key-translation-map (kbd "<apps>") (kbd "<menu>")))
(ergoemacs-theme-component pan ()
  "My personal modifications to ergoemacs-mode keys."
  (global-set-key (kbd "M-t") 'ispell-word)
  (global-set-key "\M-c" 'toggle-current-char-case)
  (global-set-key "\C-e" 'eshell)
  (global-set-key "\C-w" 'ergoemacs-close-current-buffer)
  (global-set-key (kbd "C-S-o") 'xah-open-in-external-app)
  (global-set-key (kbd "C-S-d") 'ergoemacs-open-in-desktop)
  (global-set-key (kbd "M-;") 'comment-dwim)
  (global-set-key (kbd "<menu> b") 'bbdb)
  (global-set-key "\M-s" 'other-window)  ;; (global-set-key (kbd "<f6>") 'undefined)
  )
(ergoemacs-require 'pan)
;; customize keys start with <menu>
(global-set-key (kbd "<menu>") nil)
(global-set-key (kbd "<menu> <left>") 'previous-buffer)
(global-set-key (kbd "<menu> <right>") 'next-buffer)
(global-set-key (kbd "<menu> a") 'scratch)
(global-set-key (kbd "<menu> c") 'calendar)
(global-set-key (kbd "<menu> d") 'delete-rectangle)
(global-set-key (kbd "<menu> e") 'eshell)
(global-set-key (kbd "<menu> f") 'ergoemacs-copy-full-path)
(global-set-key (kbd "<menu> g") 'insert-register)
(global-set-key (kbd "<menu> r") 'copy-rectangle-as-kill)
(global-set-key (kbd "<menu> i") 'string-insert-rectangle)
(global-set-key (kbd "<menu> j") 'jump-to-register)
(global-set-key (kbd "<menu> m") 'mu4e-update-mail-and-index)
(global-set-key (kbd "<menu> n") 'rectangle-number-lines)
(global-set-key (kbd "<menu> p") 'ergoemacs-copy-dir-path)
(global-set-key (kbd "<menu> s") 'copy-to-register)
(global-set-key (kbd "<menu> t") 'transpose-words)
(global-set-key (kbd "<menu> v") 'yank-rectangle)
(global-set-key (kbd "<menu> x") 'kill-rectangle)
(global-set-key (kbd "<menu> SPC") 'point-to-register)
(global-set-key (kbd "<menu> <menu>") 'execute-extended-command)
(global-set-key (kbd "<menu> 8") 'bookmark-set)
(global-set-key (kbd "C-\"") 'bookmark-jump)

(provide 'init-ergoemacs)
