;;  ergoemacs-mode
(setq ergoemacs-theme nil)
(setq ergoemacs-keyboard-layout "us")
(require-package 'ergoemacs-mode)
;; (setq ergoemacs-handle-ctl-c-or-ctl-x 'both)
(ergoemacs-mode 1)
;; the following remap is need only under windows' emacs
(when *windows*
  (define-key key-translation-map (kbd "<apps>") (kbd "<menu>")))
(ergoemacs-theme-component pan ()
  "My personal modifications to ergoemacs-mode keys."
  (global-set-key (kbd "M-t") 'ispell-word)
  (global-set-key "\C-e" 'eshell)
  (global-set-key (kbd "C-S-d") 'ergoemacs-open-in-desktop)
  (global-set-key (kbd "M-;") 'comment-dwim)
  (global-set-key (kbd "M-S-a") 'shell-command)
  (global-set-key (kbd "<menu> b") 'bbdb)
  )
(ergoemacs-require 'pan)
;; customize keys start with <menu>
(global-set-key (kbd "M-'") 'hippie-expand)
(global-set-key (kbd "<menu>") nil)
(global-set-key (kbd "<menu> <left>") 'previous-buffer)
(global-set-key (kbd "<menu> <right>") 'next-buffer)
(global-set-key (kbd "<menu> d") 'delete-rectangle)
(global-set-key (kbd "<menu> e") 'eshell)
(global-set-key (kbd "<menu> f") 'ergoemacs-copy-full-path)
(global-set-key (kbd "<menu> g") 'insert-register)
(global-set-key (kbd "<menu> i") 'string-insert-rectangle)
(global-set-key (kbd "<menu> j") 'jump-to-register)
(global-set-key (kbd "<menu> m") 'mu4e-update-mail-and-index)
(global-set-key (kbd "<menu> n") 'rectangle-number-lines)
(global-set-key (kbd "<menu> p") 'ergoemacs-copy-dir-path)
(global-set-key (kbd "<menu> r") 'copy-to-register)
(global-set-key (kbd "<menu> v") 'yank-rectangle)
(global-set-key (kbd "<menu> x") 'kill-rectangle)
(global-set-key (kbd "<menu> c") 'copy-rectangle-as-kill)
(global-set-key (kbd "<menu> SPC") 'point-to-register)
(global-set-key (kbd "<menu> <menu>") 'execute-extended-command)
(global-set-key (kbd "<menu> 8") 'bookmark-set)
(global-set-key (kbd "<menu> %") 'query-replace-regexp)
(global-set-key (kbd "<menu> O") 'occur)
(global-set-key (kbd "M-5") 'query-replace)
(global-set-key (kbd "M-%") 'query-replace-regexp)
(global-set-key (kbd "M-n") 'ergoemacs-beginning-or-end-of-buffer)
(global-set-key (kbd "M-i") 'cua-scroll-down)
(global-set-key (kbd "M-k") 'cua-scroll-up)
(global-set-key (kbd "C-\"") 'bookmark-jump)
(global-set-key (kbd "M-S-t") 'transpose-words)
(global-set-key (kbd "C-S-c") 'toggle-current-char-case)
(global-set-key (kbd "M-h") 'ergoemacs-beginning-of-line-or-what)
(global-set-key (kbd "M-H") 'ergoemacs-end-of-line-or-what)
(global-set-key (kbd "M-j") 'ergoemacs-backward-open-bracket)
(global-set-key (kbd "M-l") 'ergoemacs-forward-close-bracket)
(global-set-key (kbd "M-g") 'kill-line)
(global-set-key (kbd "M-x") 'zap-up-to-char)

(provide 'init-ergoemacs)
